# Generated by Django 4.2.7 on 2025-06-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('director', 'Директор'), ('printer', 'Печатник'), ('gluer', 'Клейщик страз'), ('manager', 'Менеджер по заказам'), ('packer', 'Упаковщик')], max_length=20),
        ),
    ]
