# Generated by Django 4.2.7 on 2025-06-11 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_list', models.TextField()),
                ('teacher_name', models.CharField(max_length=128)),
                ('deploy', models.DateField()),
                ('school', models.CharField(max_length=128)),
                ('class_number', models.CharField(max_length=24)),
                ('client_phone', models.CharField(max_length=20)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('rhinestones', models.BooleanField(default=False)),
                ('count_rhinestones', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('status', models.CharField(choices=[('accept', 'Принят'), ('paid', 'Оплачен'), ('printing', 'Печать'), ('gluing', 'Клейка страз'), ('packing', 'Упаковка'), ('done', 'Завершен')], default='accept', max_length=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gluer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='glued_orders', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_orders', to=settings.AUTH_USER_MODEL)),
                ('packer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packed_orders', to=settings.AUTH_USER_MODEL)),
                ('paint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='products.paints')),
                ('printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_orders', to=settings.AUTH_USER_MODEL)),
                ('ribbon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='products.ribbons')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='products.tempaltes')),
            ],
            options={
                'ordering': ['deploy'],
            },
        ),
    ]
