# Generated by Django 4.2.7 on 2025-06-03 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_list', models.FileField(upload_to='')),
                ('teacher_name', models.CharField(max_length=128)),
                ('deploy', models.DateField()),
                ('school', models.CharField(max_length=128)),
                ('class_number', models.CharField(max_length=24)),
                ('paint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='products.paints')),
                ('ribbon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='products.ribbons')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='products.tempaltes')),
            ],
        ),
    ]
