# Generated by Django 4.2.7 on 2025-06-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='class_list',
            field=models.TextField(),
        ),
    ]
