# Generated by Django 4.2.7 on 2025-06-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('accept', 'Принят'), ('paid', 'Оплачен'), ('printing', 'Печать'), ('gluing', 'Клейка страз'), ('packing', 'Упаковка'), ('done', 'Завершен')], default='accept', max_length=10),
        ),
    ]
