# Generated by Django 4.2.7 on 2025-06-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orders_class_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['deploy']},
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Принят', 'Accept'), ('Оплачено', 'Paid'), ('Напечатано', 'Printed'), ('Упакован', 'Packerd'), ('Завершен', 'Complete')], default='Принят', max_length=10),
        ),
    ]
