# Generated by Django 4.2.7 on 2025-06-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orders_count_orders_rhinestones'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='count_thinestones',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
