# Generated by Django 4.2.7 on 2025-06-07 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orders_count_thinestones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='count_thinestones',
            new_name='count_rhinestones',
        ),
    ]
