# Generated by Django 4.2.7 on 2025-06-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_count_thinestones_orders_count_rhinestones'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
