# Generated by Django 4.2.7 on 2025-06-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ribbons',
            name='color',
            field=models.CharField(max_length=48, unique=True),
        ),
    ]
