# Generated by Django 4.2.7 on 2025-06-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_ribbons_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ribbons',
            name='color',
            field=models.CharField(max_length=48),
        ),
    ]
